---
output:
  pdf_document: default
  html_document: default
---
```{r}
library(tidyverse)
library(taRifx)
library(ggrepel)
library(psych)
library(lavaan)
library(semPlot)
library(MVN)
library(infotheo)
source('MultipleDiscreteMI.R', local = TRUE)
source('C:/Users/Cole/Documents/GitHub/PLIC/Process-Merge-Concat/PLIC_DataProcessing.R')
```

**Create PLIC dataframe**
```{r}
df_full <- read.csv('C:/Users/Cole/Box Sync/PLIC_DATA/Collective_Surveys/Complete/Complete_Concat.csv')

ScoresList <- c('Q1Bs', 'Q1Ds', 'Q1Es', 'Q2Bs', 'Q2Ds', 'Q2Es', 'Q3Bs', 'Q3Ds', 'Q3Es', 'Q4Bs')
OthersList <- c('Q1b_19', 'Q1d_10', 'Q1e_12', 'Q2b_38', 'Q2d_11', 'Q2e_11', 'Q3b_10', 'Q3d_29', 'Q3e_8', 'Q4b_11')

df_Pre <- df_full %>%
  filter((Survey_x == 'C') & (!is.na(PreScores)) & (!is.na(Q3c_x))) %>%
  select(c(grep(paste('((Q1b|Q1d|Q1e|Q2b|Q2d|Q2e|Q3b|Q3d|Q3e|Q4b)_[0-9]*)', 'x', sep = '_'),
                names(.))), paste(ScoresList, 'x', sep = '_')) %>%
  `colnames<-`(gsub(x = names(.), pattern = "\\_x", replacement = "")) %>%
  select(-OthersList)

df_Post <- df_full %>%
  filter((Survey_y == 'C') & (!is.na(PostScores)) & (!is.na(Q3c_y))) %>%
  select(c(grep(paste('((Q1b|Q1d|Q1e|Q2b|Q2d|Q2e|Q3b|Q3d|Q3e|Q4b)_[0-9]*)', 'y', sep = '_'),
                names(.))), paste(ScoresList, 'y', sep = '_')) %>%
  `colnames<-`(gsub(x = names(.), pattern = "\\_y", replacement = "")) %>%
  select(-OthersList)

df <- rbind(df_Pre, df_Post)

char_vars <- lapply(df, class) == "character"
df[, char_vars] <- lapply(df[, char_vars], as.factor)

df <- df %>%
  japply(., which(sapply(., class) == 'factor'), function(x) as.numeric(levels(x))[x])

df[is.na(df)] <- 0
df_Questions <- df[, ScoresList]
df_Items <- df %>%
  select(-ScoresList)

df.Class <- Merge.CIS(df_full)
length(unique(df.Class$Class_ID))
length(unique(df.Class$School))
nrow(df_Items)
unique(df.Class$School)

table(df.Class[!duplicated(df.Class$Class_ID),]$Lab_Level, exclude = NULL)
table(df.Class[!duplicated(df.Class$School),]$Institution_Type, exclude = NULL)
```

**CFA on test dataset with hypothesized model**
```{r}
# mvn(df_Questions, univariatePlot = 'histogram')
PLIC.model.HYP <- ' models  =~ Q1Bs + Q2Bs + Q3Bs + Q3Ds
              methods =~ Q1Ds + Q2Ds + Q4Bs
              actions =~ Q1Es + Q2Es + Q3Es '

mod.cfa.HYP <- cfa(PLIC.model.HYP, data = df_Questions, std.lv = TRUE, estimator = 'ML')

summary(mod.cfa.HYP, fit.measures = TRUE, modindices = TRUE, standardized = TRUE)
resid(mod.cfa.HYP)
cor(df_Questions)
semPaths(mod.cfa.HYP, what = 'diagram', whatLabels = 'stand', layout = 'tree2', residuals = FALSE, nCharNodes = 10, edge.color = 'black', edge.label.cex = 2, curve = 2, label.scale = FALSE, nodeLabels = c('Q1B', 'Q2B', 'Q3B', 'Q3D', 'Q1D', 'Q2D', 'Q4B', 'Q1E', 'Q2E', 'Q3E', 'Evaluate\nModels', 'Evaluate\nMethods', 'Suggest\nFollow-ups'), rotation = 2, sizeMan = 8, sizeLat = 18, width = 4, height = 5, filetype = 'png', mar = c(1, 6, 1, 2))
```

**Mutual Information for Single Factors**
```{r}
scores.df <- data.frame(lavPredict(mod.cfa.HYP))

N_models <- floor((max(scores.df$models) - min(scores.df$models))/(3.5 * sd(scores.df$models)/(nrow(scores.df)^(1/3))))
N_methods <- floor((max(scores.df$methods) - min(scores.df$methods))/(3.5 * sd(scores.df$methods)/(nrow(scores.df)^(1/3))))
N_actions <- floor((max(scores.df$actions) - min(scores.df$actions))/(3.5 * sd(scores.df$actions)/(nrow(scores.df)^(1/3))))

scores <- data.frame(discretize(scores.df$models, nbins = N_models), discretize(scores.df$methods, nbins = N_methods), discretize(scores.df$actions, nbins = N_actions))

colnames(scores) <- c('models', 'methods', 'actions')

Models.df <- df_Items[, grep('Q1b|Q2b|Q3b|Q3d', names(df_Items))]

Models.MI.df <- MI.CI(Models.df, scores$models, reps = 1000)

labels.list <- c('Q2B_9', 'Q2B_21', 'Q3B_9', 'Q3B_21', 'Q2B_11', 'Q3B_11', 'Q2B_8', 'Q3B_23')

ggplot(Models.MI.df, aes(x = Prop.Sel, y = MI, color = Question, shape = Question)) +
  geom_point(size = 3.5, alpha = 0.25) +
  geom_errorbar(aes(ymin = CI.Low, ymax = CI.High), width = 0.01, size = 1, alpha = 0.25) +
  geom_point(data = Models.MI.df[Models.MI.df[, 'Item'] %in% labels.list,], aes(x = Prop.Sel, y = MI, color = Question), size = 3.5) +
  geom_errorbar(data = Models.MI.df[Models.MI.df[, 'Item'] %in% labels.list,], aes(ymin = CI.Low, ymax = CI.High), width = 0.01, size = 0.8, alpha = 1) +
  scale_shape_manual(values = c(15, 16, 17, 18)) +
  scale_color_manual(values = c("#0072b2", "#d55e00", "#009e73", "#009e73")) +
  scale_fill_manual(values = labels.list) +
  geom_text_repel(data = subset(Models.MI.df, Item %in% labels.list),
            aes(x = Prop.Sel, y = MI, color = Question, label = Item), nudge_x = 0.02, nudge_y = 0.03, size = 6) +
  theme_classic() +
  theme(text = element_text(size = 18)) +
  labs(x = 'Fraction of times selected', y = 'Mutual information (bits)') +
  ylim(0, 0.31)
```

```{r}
scores <- discretize(scores.df, nbins = N_methods)

Methods.df <- df_Items[, grep('Q1d|Q2d|Q4b', names(df_Items))]

Methods.MI.df <- sapply(Methods.df, MI.vec.to.bits, df_Features = scores$methods) %>%
  data.frame(.) %>%
  `colnames<-`(c("MI")) %>%
  mutate(Item = sapply(colnames(Methods.df), function(x) toupper(x)),
        Prop.Sel = round(colMeans(Methods.df), 3),
        Question = sapply(Item, function(x) toupper(substr(x, 1, 3)))) %>%
    select(Item, Question, Prop.Sel, MI) %>%
  arrange(desc(MI))

Methods.MI.df <- MI.CI(Methods.df, scores$methods, reps = 1000)

Methods.MI.df
labels.list <- c('Q1D_61', 'Q1D_63', 'Q2D_35', 'Q2D_4', 'Q1D_3', 'Q2D_33', 'Q4B_4')

ggplot(Methods.MI.df, aes(x = Prop.Sel, y = MI, color = Question, shape = Question)) +
  geom_point(size = 3.5, alpha = 0.25) +
  geom_errorbar(aes(ymin = CI.Low, ymax = CI.High), width = 0.01, size = 1, alpha = 0.25) +
  geom_point(data = Methods.MI.df[Methods.MI.df[, 'Item'] %in% labels.list,], aes(x = Prop.Sel, y = MI, color = Question), size = 3.5) +
  geom_errorbar(data = Methods.MI.df[Methods.MI.df[, 'Item'] %in% labels.list,], aes(ymin = CI.Low, ymax = CI.High), width = 0.01, size = 0.8, alpha = 1) +
  scale_shape_manual(values = c(15, 16, 17)) +
  scale_color_manual(values = c("#0072b2", "#d55e00", "#cc79a7")) +
  scale_fill_manual(values = labels.list) +
  geom_text_repel(data = subset(Methods.MI.df, Item %in% labels.list),
            aes(x = Prop.Sel, y = MI, color = Question, label = Item), nudge_x = 0.02, nudge_y = 0.06, size = 6) +
  theme_classic() +
  theme(text = element_text(size = 18)) +
  labs(x = 'Fraction of times selected', y = 'Mutual information (bits)')
```

```{r}
scores <- discretize(scores.df, nbins = N_actions)

Actions.df <- df_Items[, grep('Q1e|Q2e|Q3e', names(df_Items))]

Actions.MI.df <- sapply(Actions.df, MI.vec.to.bits, df_Features = scores$actions) %>%
  data.frame(.) %>%
  `colnames<-`(c("MI")) %>%
  mutate(Item = sapply(colnames(Actions.df), function(x) toupper(x)),
        Prop.Sel = round(colMeans(Actions.df), 3),
        Question = sapply(Item, function(x) toupper(substr(x, 1, 3)))) %>%
    select(Item, Question, Prop.Sel, MI) %>%
  arrange(desc(MI))

Actions.MI.df <- MI.CI(Actions.df, scores$actions, CI.Low = 0.025, CI.High = 0.975)

Actions.MI.df
labels.list <- c('Q1E_1', 'Q1E_4', 'Q1E_13', 'Q2E_14', 'Q2E_6', 'Q3E_11', 'Q3E_13', 'Q3E_20')

ggplot(Actions.MI.df, aes(x = Prop.Sel, y = MI, color = Question, shape = Question)) +
  geom_point(size = 3.5, alpha = 0.25) +
  geom_errorbar(aes(ymin = CI.Low, ymax = CI.High), width = 0.01, size = 1, alpha = 0.25) +
  geom_point(data = Actions.MI.df[Actions.MI.df[, 'Item'] %in% labels.list,], aes(x = Prop.Sel, y = MI, color = Question), size = 3.5) +
  geom_errorbar(data = Actions.MI.df[Actions.MI.df[, 'Item'] %in% labels.list,], aes(ymin = CI.Low, ymax = CI.High), width = 0.01, size = 0.8, alpha = 1) +
  scale_shape_manual(values = c(15, 16, 17)) +
  scale_color_manual(values = c("#0072b2", "#d55e00", "#009e73")) +
  scale_fill_manual(values = labels.list) +
  geom_text_repel(data = subset(Actions.MI.df, Item %in% labels.list),
            aes(x = Prop.Sel, y = MI, color = Question, label = Item), nudge_x = 0.04, nudge_y = 0.01, size = 6) +
  theme_classic() +
  theme(text = element_text(size = 18)) +
  labs(x = 'Fraction of times selected', y = 'Mutual information (bits)')
```

```{r}
Full.MI.df <- sapply(df_Items, MI.vec.to.bits, df_Features = scores) %>%
  data.frame(.) %>%
  `colnames<-`(c("MI")) %>%
  mutate(Item = sapply(colnames(df_Items), function(x) toupper(x)),
        Prop.Sel = round(colMeans(df_Items), 3),
        Question = sapply(Item, function(x) toupper(substr(x, 1, 3)))) %>%
    select(Item, Question, Prop.Sel, MI) %>%
  arrange(desc(MI))
scores
Full.MI.df

ggplot(Full.MI.df, aes(x = Prop.Sel, y = MI, color = Question)) +
  geom_point() +
  theme_classic() +
  theme(text = element_text(size = 12)) +
  labs(x = 'Fraction of times selected', y = 'Mutual information with evaluating models scale (bits)')
```

