---
output:
  pdf_document: default
  html_document: default
---
# Load necessary packages
```{r, message = FALSE, warning = FALSE, echo = FALSE}
library(tidyverse)
library(DescTools)
library(ryouready)
library(reshape2)
library(stringr)
library(ggthemes)
theme_set(theme_fivethirtyeight())
```

# Load file and do some preprocessing
```{r, echo = FALSE, results = FALSE}
file = 'C:/Users/Cole/Documents/DATA/PLIC_DATA/Experts/Experts_v08042020_09202020.csv'

info <- data.frame(lapply(read.csv(file, nrows = 1), 
                          FUN = function(x) gsub("^.*- ", "", x)))

headers = read.csv(file, header = F, nrows = 1, as.is = T)
headers <- data.frame(lapply(headers, function(x) sub(' ', '.', x)))
df = read.csv(file, header = F)
df <- df %>%
  tail(., nrow(df) - 3) %>%
  `colnames<-`(headers) %>%
  filter(Finished == 1) %>%
  filter((Qt1_Page.Submit > 30) | (Qt2_Page.Submit > 30) | (Qt3_Page.Submit > 30) |
           (Qt4_Page.Submit > 30)) %>%
  filter(!(Q6a %in% c(1, 4)))

# check which entries to manually delete
df[df$Q6a %in% c(8, 9), c('Q6a', 'Q6a_8_TEXT')]
df <- df[!(row.names(df) %in% c(4, 16)),]

df <- recode2(df, vars = colnames(df)[colnames(df) %like any% c('%Q139%',
                                                                '%Q140%', 
                                                                '%Q141%',
                                                                '%Q157%')], 
              recodes = "6 = 1; 7 = 2; 9 = 3; 10 = 4")
df <- recode2(df, vars = c('Q1a'), recodes = "1 = 1; 2 = 2; 5 = 3; 3 = 4")
df <- recode2(df, vars = c('Q133'), recodes = "1 = 1; 2 = 2; 5 = 3; 6 = 4")
df <- recode2(df, vars = c('Q1a', 'Q2a', 'Q3a'), recodes = "1 = 'Support'; 
              2 = 'Refute'; 3 = 'Neither'; 4 = 'More evidence'")
df <- recode2(df, vars = c('Q133', 'Q144', 'Q148'), 
              recodes = "1 = 'Data collection'; 2 = 'Amount of data'; 
                          3 = 'Analysis'; 4 = 'Others'")
df <- recode2(df, vars = c('Q3c'), 
              recodes = "1 = 'fixed at zero'; 2 = 'not fixed at zero'; 
                          3 = 'other'")
df <- recode2(df, vars = c('Q4a'), 
                recodes = "1 = 'Group 1'; 2 = 'Group 2'; 3 = 'Both'; 
                            4 = 'Neither'")
df <- recode2(df, vars = colnames(df)[colnames(df) %like any% c('%Q152%',
                                                                '%Q153%', 
                                                                '%Q154%')], 
                recodes = "1 = '1'; 2 = '2'; 3 = 'B'; 4 = 'N'")
```

# Analysis

## Page 1
```{r, echo = FALSE}
print('What do you think Group 1 should say about whether their data agree with 
      the model?')

ggplot(df, aes(x = factor(Q1a), fill = factor(Q1a))) +
  geom_bar(aes(y = (..count..)/sum(..count..))) +
  ggtitle('Group 1, data agree with the model') +
  theme(legend.position = "none")

print('Which statements below support your reasoning for whether Group 1s data 
      agree with the model?')

cols.temp <- colnames(df)[(colnames(df) %like% '%Q1b%') & 
                            !(colnames(df) %like% '%TEXT%')]

df.temp <- df[, cols.temp] %>%
  melt(., measure.vars = cols.temp) %>%
  mutate(value = ifelse(value == 1, 1, 0))

data.frame(t(info[, cols.temp]))

ggplot(df.temp, aes(x = variable, fill = variable, y = value/nrow(df))) +
  geom_bar(stat = 'identity')  +
  ggtitle('Group 1, reasoning') +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 30, vjust = 0.5, hjust = 1))

print('Group 1 evaluate methods')

cols.temp <- colnames(df)[(colnames(df) %like% '%Q139%') & 
                            !(colnames(df) %like% '%TEXT%')]

df.temp <- df[, cols.temp] %>%
  melt(., measure.vars = cols.temp) %>%
  mutate(variable = case_when(
    variable == 'Q139_1' ~ 'Equipment used',
    variable == 'Q139_2' ~ 'Variables measured',
    variable == 'Q139_3' ~ 'Variables controlled',
    TRUE ~ NA_character_
  )) %>%
  filter(!is.na(variable) & value != '')

ggplot(df.temp, aes(x = factor(value), fill = factor(value))) +
  geom_bar(aes(y = (..count..)/nrow(df))) +
  ggtitle('Group 1, data collection methods') +
  theme(legend.position = "none") +
  facet_wrap(~variable)

cols.temp <- colnames(df)[(colnames(df) %like% '%Q140%') & 
                            !(colnames(df) %like% '%TEXT%')]

df.temp <- df[, cols.temp] %>%
  melt(., measure.vars = cols.temp) %>%
  mutate(variable = case_when(
    variable == 'Q140_1' ~ 'N trials',
    variable == 'Q140_2' ~ 'N masses',
    variable == 'Q140_3' ~ 'N bounces',
    TRUE ~ NA_character_
  )) %>%
  filter(!is.na(variable) & value != '')

ggplot(df.temp, aes(x = factor(value), fill = factor(value))) +
  geom_bar(aes(y = (..count..)/nrow(df))) +
  ggtitle('Group 1, amount of data') +
  theme(legend.position = "none") +
  facet_wrap(~variable)

cols.temp <- colnames(df)[(colnames(df) %like% '%Q141%') & 
                            !(colnames(df) %like% '%TEXT%')]

df.temp <- df[, cols.temp] %>%
  melt(., measure.vars = cols.temp) %>%
  mutate(variable = case_when(
    variable == 'Q141_1' ~ 'Explanations',
    variable == 'Q141_2' ~ 'Analysis',
    variable == 'Q141_3' ~ 'Similar k values',
    variable == 'Q141_4' ~ 'Uncertainty in data and k',
    TRUE ~ NA_character_
  )) %>%
  filter(!is.na(variable) & value != '')

ggplot(df.temp, aes(x = factor(value), fill = factor(value))) +
  geom_bar(aes(y = (..count..)/nrow(df))) +
  ggtitle('Group 1, analysis and outcomes') +
  theme(legend.position = "none") +
  facet_wrap(~variable)

print('How effective do you think Group 1s method was for testing whether the 
      data obey the model?')

ggplot(df, aes(x = factor(Q1c), fill = factor(Q1c))) +
  geom_bar(aes(y = (..count..)/sum(..count..))) +
  ggtitle('Group 1, method effectiveness') +
  theme(legend.position = "none")

print('What feature was most important to you in evaluating the effectiveness of 
      Group 1s methods (either as strengths or weaknesses)?')

ggplot(df, aes(x = factor(Q133), fill = factor(Q133))) +
  geom_bar(aes(y = (..count..)/sum(..count..))) +
  ggtitle('Group 1, feature of method') +
  theme(legend.position = "none")

print('What do you think Group 1 should do next?')

cols.temp <- colnames(df)[(colnames(df) %like% '%Q134%') & 
                            !(colnames(df) %like% '%TEXT%')]

df.temp <- df[, cols.temp] %>%
  melt(., measure.vars = cols.temp) %>%
  mutate(value = ifelse(value == 1, 1, 0))

data.frame(t(info[, cols.temp]))

ggplot(df.temp, aes(x = variable, fill = variable, y = value/nrow(df))) +
  geom_bar(stat = 'identity')  +
  ggtitle('Group 1, what to do next') +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 30, vjust = 0.5, hjust = 1))
```

## Page 2
```{r, echo = FALSE}
print('What do you think Group 2 should say about whether their data agree with 
      the model?')

ggplot(df, aes(x = factor(Q2a), fill = factor(Q2a))) +
  geom_bar(aes(y = (..count..)/sum(..count..))) +
  ggtitle('Group 2, data agree with the model') +
  theme(legend.position = "none")

print('Which statements below support your reasoning for whether Group 2s data 
      agree with the model?')

cols.temp <- colnames(df)[(colnames(df) %like% '%Q2b%') & 
                            !(colnames(df) %like% '%TEXT%')]

df.temp <- df[, cols.temp] %>%
  melt(., measure.vars = cols.temp) %>%
  mutate(value = ifelse(value == 1, 1, 0))

data.frame(t(info[, cols.temp]))

ggplot(df.temp, aes(x = variable, fill = variable, y = value/nrow(df))) +
  geom_bar(stat = 'identity')  +
  ggtitle('Group 2, reasoning') +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 30, vjust = 0.5, hjust = 1))

print('Group 2 evaluate methods')

cols.temp <- colnames(df)[(colnames(df) %like% '%Q2d%') & 
                            !(colnames(df) %like% '%TEXT%')]

df.temp <- df[, cols.temp] %>%
  melt(., measure.vars = cols.temp) %>%
  mutate(variable = case_when(
    variable == 'Q2d_1' ~ 'Equipment used',
    variable == 'Q2d_2' ~ 'Variables measured',
    variable == 'Q2d_3' ~ 'Variables controlled',
    TRUE ~ NA_character_
  )) %>%
  filter(!is.na(variable) & value != '')

ggplot(df.temp, aes(x = factor(value), fill = factor(value))) +
  geom_bar(aes(y = (..count..)/nrow(df))) +
  ggtitle('Group 2, data collection methods') +
  theme(legend.position = "none") +
  facet_wrap(~variable)

cols.temp <- colnames(df)[(colnames(df) %like% '%Q142%') & 
                            !(colnames(df) %like% '%TEXT%')]

df.temp <- df[, cols.temp] %>%
  melt(., measure.vars = cols.temp) %>%
  mutate(variable = case_when(
    variable == 'Q142_1' ~ 'N trials',
    variable == 'Q142_2' ~ 'N masses',
    variable == 'Q142_3' ~ 'N bounces',
    TRUE ~ NA_character_
  )) %>%
  filter(!is.na(variable) & value != '')

ggplot(df.temp, aes(x = factor(value), fill = factor(value))) +
  geom_bar(aes(y = (..count..)/nrow(df))) +
  ggtitle('Group 2, amount of data') +
  theme(legend.position = "none") +
  facet_wrap(~variable)

cols.temp <- colnames(df)[(colnames(df) %like% '%Q157%') & 
                            !(colnames(df) %like% '%TEXT%')]

df.temp <- df[, cols.temp] %>%
  melt(., measure.vars = cols.temp) %>%
  mutate(variable = case_when(
    variable == 'Q157_1' ~ 'Explanations',
    variable == 'Q157_2' ~ 'Analysis',
    variable == 'Q157_3' ~ 'Similar k values',
    variable == 'Q157_4' ~ 'Uncertainty in data and k',
    TRUE ~ NA_character_
  )) %>%
  filter(!is.na(variable) & value != '')

ggplot(df.temp, aes(x = factor(value), fill = factor(value))) +
  geom_bar(aes(y = (..count..)/nrow(df))) +
  ggtitle('Group 2, analysis and outcomes') +
  theme(legend.position = "none") +
  facet_wrap(~variable)

print('How effective do you think Group 2s method was for testing whether the data 
      obey the model?')

ggplot(df, aes(x = factor(Q2c), fill = factor(Q2c))) +
  geom_bar(aes(y = (..count..)/sum(..count..))) +
  ggtitle('Group 2, method effectiveness') +
  theme(legend.position = "none")

print('What feature was most important to you in evaluating the effectiveness of 
      Group 2s methods (either as strengths or weaknesses)?')

ggplot(df, aes(x = factor(Q144), fill = factor(Q144))) +
  geom_bar(aes(y = (..count..)/sum(..count..))) +
  ggtitle('Group 2, feature of method') +
  theme(legend.position = "none")

print('What do you think Group 2 should do next?')

cols.temp <- colnames(df)[(colnames(df) %like% '%Q2e%') & 
                            !(colnames(df) %like% '%TEXT%')]

df.temp <- df[, cols.temp] %>%
  melt(., measure.vars = cols.temp) %>%
  mutate(value = ifelse(value == 1, 1, 0))

data.frame(t(info[, cols.temp]))

ggplot(df.temp, aes(x = variable, fill = variable, y = value/nrow(df))) +
  geom_bar(stat = 'identity')  +
  ggtitle('Group 2, what to do next') +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 30, vjust = 0.5, hjust = 1))
```

## Page 3
```{r, echo = FALSE}
print('What do you think Group 2 should say about whether their data agree with 
      the model?')

ggplot(df, aes(x = factor(Q3a), fill = factor(Q3a))) +
  geom_bar(aes(y = (..count..)/sum(..count..))) +
  ggtitle('Group 2, data agree with the model') +
  theme(legend.position = "none")

print('Which statements below support your reasoning for whether Group 2s data 
      agree with the model?')

cols.temp <- colnames(df)[(colnames(df) %like% '%Q145%') & 
                            !(colnames(df) %like% '%TEXT%')]

df.temp <- df[, cols.temp] %>%
  melt(., measure.vars = cols.temp) %>%
  mutate(value = ifelse(value == 1, 1, 0))

data.frame(t(info[, cols.temp]))

ggplot(df.temp, aes(x = variable, fill = variable, y = value/nrow(df))) +
  geom_bar(stat = 'identity')  +
  ggtitle('Group 2, reasoning') +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 30, vjust = 0.5, hjust = 1))

print('Which fit do you think Group 2 should use?')

ggplot(df, aes(x = factor(Q3c), fill = factor(Q3c))) +
  geom_bar(aes(y = (..count..)/sum(..count..))) +
  ggtitle('Group 2, which fit') +
  theme(legend.position = "none")

print('Others: Either fix the intercept at zero or change the model., both, 
      I think the results of both fits should be discussed, including whether 
      there is a natural explanation for adding an intercept in a revised model')

print('Which items below best reflect your reasoning?')

cols.temp <- colnames(df)[(colnames(df) %like% '%Q3d%') & 
                            !(colnames(df) %like% '%TEXT%')]

df.temp <- df[, cols.temp] %>%
  melt(., measure.vars = cols.temp) %>%
  mutate(value = ifelse(value == 1, 1, 0))

data.frame(t(info[, cols.temp]))

ggplot(df.temp, aes(x = variable, fill = variable, y = value/nrow(df))) +
  geom_bar(stat = 'identity')  +
  ggtitle('Group 2, reasoning for fit') +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 30, vjust = 0.5, hjust = 1))

print('What do you think Group 2 should do next?')

cols.temp <- colnames(df)[(colnames(df) %like% '%Q147%') & 
                            !(colnames(df) %like% '%TEXT%')]

df.temp <- df[, cols.temp] %>%
  melt(., measure.vars = cols.temp) %>%
  mutate(value = ifelse(value == 1, 1, 0))

data.frame(t(info[, cols.temp]))

ggplot(df.temp, aes(x = variable, fill = variable, y = value/nrow(df))) +
  geom_bar(stat = 'identity')  +
  ggtitle('Group 2, what to do next') +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 30, vjust = 0.5, hjust = 1))
```

## Page 4
```{r, echo = FALSE}
print('Which group do you think did a better job of testing the model?')

ggplot(df, aes(x = factor(Q4a), fill = factor(Q4a))) +
  geom_bar(aes(y = (..count..)/sum(..count..))) +
  ggtitle('Which group did a better job?') +
  theme(legend.position = "none")

print('Compare methods')

cols.temp <- colnames(df)[(colnames(df) %like% '%152%') & 
                            !(colnames(df) %like% '%TEXT%')]

df.temp <- df[, cols.temp] %>%
  melt(., measure.vars = cols.temp) %>%
  mutate(variable = case_when(
    variable == 'Q152_1' ~ 'Equipment used',
    variable == 'Q152_2' ~ 'Variables measured',
    variable == 'Q152_3' ~ 'Variables controlled',
    TRUE ~ NA_character_
  )) %>%
  filter(!is.na(variable) & value != '')

ggplot(df.temp, aes(x = factor(value), fill = factor(value))) +
  geom_bar(aes(y = (..count..)/nrow(df))) +
  ggtitle('Compare data collection methods') +
  theme(legend.position = "none") +
  facet_wrap(~variable)

cols.temp <- colnames(df)[(colnames(df) %like% '%Q153%') & 
                            !(colnames(df) %like% '%TEXT%')]

df.temp <- df[, cols.temp] %>%
  melt(., measure.vars = cols.temp) %>%
  mutate(variable = case_when(
    variable == 'Q153_1' ~ 'N trials',
    variable == 'Q153_2' ~ 'N masses',
    variable == 'Q153_3' ~ 'N bounces',
    TRUE ~ NA_character_
  )) %>%
  filter(!is.na(variable) & value != '')

ggplot(df.temp, aes(x = factor(value), fill = factor(value))) +
  geom_bar(aes(y = (..count..)/nrow(df))) +
  ggtitle('Compare amount of data') +
  theme(legend.position = "none") +
  facet_wrap(~variable)

cols.temp <- colnames(df)[(colnames(df) %like% '%Q154%') & 
                            !(colnames(df) %like% '%TEXT%')]

df.temp <- df[, cols.temp] %>%
  melt(., measure.vars = cols.temp) %>%
  mutate(variable = case_when(
    variable == 'Q154_1' ~ 'Explanations',
    variable == 'Q154_2' ~ 'Analysis',
    variable == 'Q154_3' ~ 'Similar k values',
    variable == 'Q154_4' ~ 'Uncertainty in data and k',
    TRUE ~ NA_character_
  )) %>%
  filter(!is.na(variable) & value != '')

ggplot(df.temp, aes(x = factor(value), fill = factor(value))) +
  geom_bar(aes(y = (..count..)/nrow(df))) +
  ggtitle('Compare analysis and outcomes') +
  theme(legend.position = "none") +
  facet_wrap(~variable)

print('What feature was most important to you for comparing the two groups?')

ggplot(df, aes(x = factor(Q148), fill = factor(Q148))) +
  geom_bar(aes(y = (..count..)/sum(..count..))) +
  ggtitle('Feature for comparing methods') +
  theme(legend.position = "none")
```





