```{r}
library(tidyverse)
library(data.table)
library(effsize)
library(lme4)
library(lmerTest)
library(MuMIn)
library(stargazer)
library(lavaan)
library(semPlot)
library(mice)
library(miceadds)
library(mitml)
library(sjstats)
library(dotwhisker)
source('C:/Users/Cole/Documents/PLIC_DATA/PLIC_DataProcessing.R')
theme_set(theme_classic(base_size = 18))
```

**Import merged data**
```{r}
# Overall class/school breakdown
PLIC.Complete.df <- fread('C:/Users/Cole/Documents/PLIC_DATA/Collective_Surveys/Complete/Complete_Concat.csv') %>%
#   mutate(PreScores = ifelse(Survey_x == 'C', PreScores, NA_real_),
#          PostScores = ifelse(Survey_y == 'C', PostScores, NA_real_)) %>%
#   filter(!is.na(PreScores) | !is.na(PostScores)) %>%
  Clean.PLIC(.) %>%
  Merge.CIS(.)
PLIC.Complete.df %>%
  summarize(N.Students = nrow(.), N.Classes = length(unique(.[, 'Class_ID'])), N.Schools = length(unique(.[, 'School'])))
table(PLIC.Complete.df[!duplicated(PLIC.Complete.df$School),]$Institution_Type, exclude = NULL)
table(PLIC.Complete.df[!duplicated(PLIC.Complete.df$Class_ID),]$Lab_Level, exclude = NULL)

# Gender non-binaries?
table(PLIC.Complete.df$Gender, exclude = NULL)

# Only complete demographics
PLIC.CompleteDemos.df <- PLIC.Complete.df %>%
  filter(!is.na(Gender) & !is.na(Ethnicity) & !is.na(Major))
PLIC.CompleteDemos.df %>%
  summarize(N.Students = nrow(.), N.Classes = length(unique(.[, 'Class_ID'])), N.Schools = length(unique(.[, 'School'])))
table(PLIC.CompleteDemos.df[!duplicated(PLIC.CompleteDemos.df$School),]$Institution_Type, exclude = NULL)
table(PLIC.CompleteDemos.df[!duplicated(PLIC.CompleteDemos.df$Class_ID),]$Lab_Level, exclude = NULL)

# Remove courses
PLIC.CompletePreCourses.df <- data.table(PLIC.CompleteDemos.df)[, `:=`(N.Pre = sum(!is.na(PreScores))/.N, N.Post = sum(!is.na(PostScores))/.N), by = Class_ID]
print(nrow(PLIC.CompletePreCourses.df[!duplicated(PLIC.CompletePreCourses.df$Class_ID) & PLIC.CompletePreCourses.df$N.Pre == 0]))

PLIC.CompletePreCourses.df <- PLIC.CompletePreCourses.df[N.Pre > .4] %>%
  mutate(Lab_Level = relevel(as.factor(case_when(
    (Lab_Level == 'Intro-Algebra') | (Lab_Level == 'Intro-Calculus') ~ 'FY',
    (Lab_Level == 'Sophomore') | (Lab_Level == 'Junior') | (Lab_Level == 'Senior') ~ 'BFY',
    TRUE ~ NA_character_
  )), ref = 'FY'))  %>%
  filter(Q27 != '') %>%
  mutate(Purpose = factor(case_when(
    Q27 == 1 ~ 'Reinforce.concepts',
    Q27 == 2 ~ 'Develop.lab.skills',
    Q27 == 3 ~ 'Both.about.equally',
    TRUE ~ NA_character_
  ), levels = c('Reinforce.concepts', 'Develop.lab.skills', 'Both.about.equally'))) 

PLIC.CompletePreCourses.df %>%
  summarize(N.Students = nrow(.), N.Classes = length(unique(PLIC.CompletePreCourses.df[, 'Class_ID'])), N.Schools = length(unique(.[, 'School'])))

PLIC.PreOnly <- PLIC.CompletePreCourses.df %>%
  filter(Survey_x == 'C' | Survey_x == 'F')

PLIC.PreOnly %>%
  summarize(N.Students = nrow(.), N.Classes = length(unique(PLIC.CompletePreCourses.df[, 'Class_ID'])), N.Schools = length(unique(.[, 'School'])))

table(PLIC.PreOnly[!duplicated(PLIC.PreOnly$School),]$Institution_Type, exclude = NULL)
table(PLIC.PreOnly[!duplicated(PLIC.PreOnly$Class_ID),]$Lab_Level, exclude = NULL)

PLIC.PreOnly$GenW <- PLIC.PreOnly$Gender == 'Women'
PLIC.PreOnly$MajorEng <- PLIC.PreOnly$Major == 'Engineering'
PLIC.PreOnly$MajorPhys <- PLIC.PreOnly$Major == 'Physics'

PLIC.PreOnly.CR <- PLIC.PreOnly %>%
  filter(Survey_x == 'C')

PLIC.PreOnly.CR %>%
  summarize(N.Students = nrow(.), N.Classes = length(unique(PLIC.CompletePreCourses.df[, 'Class_ID'])), N.Schools = length(unique(.[, 'School'])))
```

**Demographic Breakdown for matched data**
```{r}
table(PLIC.PreOnly$Major)
table(PLIC.PreOnly$Lab_Level, exclude = NULL)
table(PLIC.PreOnly$Gender, exclude = NULL)
table(PLIC.PreOnly$Gender, PLIC.PreOnly$Major)
table(PLIC.PreOnly$Gender, PLIC.PreOnly$Lab_Level)
table(PLIC.PreOnly$URM_Status)
table(PLIC.PreOnly$URM_Status, PLIC.PreOnly$Major)
table(PLIC.PreOnly$URM_Status, PLIC.PreOnly$Lab_Level)
```


**Descriptive Stats**
```{r}
PLIC.PreOnly.CR %>%
  group_by(Gender) %>%
  summarize(n(), mean(PreScores), sd(PreScores)/sqrt(n()))

PLIC.PreOnly.CR %>%
  group_by(URM_Status) %>%
  summarize(n(), mean(PreScores), sd(PreScores)/sqrt(n()))

PLIC.PreOnly.CR %>%
  group_by(Major) %>%
  summarize(n(), mean(PreScores), sd(PreScores)/sqrt(n()))

PLIC.PreOnly.CR %>%
  group_by(Lab_Level) %>%
  summarize(n(), mean(PreScores), sd(PreScores)/sqrt(n()))
```

**Pairwise comparisons**
```{r}
t.test(PreScores ~ Gender, PLIC.PreOnly.CR)
cohen.d(PreScores ~ Gender, PLIC.PreOnly.CR)

t.test(PreScores ~ URM_Status, PLIC.PreOnly.CR)
cohen.d(PreScores ~ URM_Status, PLIC.PreOnly.CR)
```



**LMER PRE**
```{r}
mod_null <- lmer(PreScores ~ (1 | Class_ID), PLIC.PreOnly.CR)
summary(mod_null)
r.squaredGLMM(mod_null)

mod_student <- lmer(PreScores ~ Gender + Major + URM_Status + (1 | Class_ID), PLIC.PreOnly.CR)
summary(mod_student)
r.squaredGLMM(mod_student)

mod_course <- lmer(PreScores ~ Gender + Major + URM_Status + Lab_Level + (1 | Class_ID), PLIC.PreOnly.CR)
summary(mod_course)
r.squaredGLMM(mod_course)

mod_interaction <- lmer(PreScores ~ Gender*URM_Status + Major + Lab_Level + (1 | Class_ID), PLIC.PreOnly.CR)
summary(mod_interaction)
r.squaredGLMM(mod_interaction)

mod_interactionMajor <- lmer(PreScores ~ (Gender + URM_Status)*Major + Lab_Level + (1 | Class_ID), PLIC.PreOnly.CR)
summary(mod_interactionMajor)
r.squaredGLMM(mod_interactionMajor)

class(mod_null) <- "lmerMod"
class(mod_student) <- "lmerMod"
class(mod_course) <- "lmerMod"
class(mod_interaction) <- "lmerMod"
class(mod_interactionMajor) <- "lmerMod"
stargazer(mod_null, mod_student, mod_course, mod_interaction, mod_interactionMajor, star.cutoffs = c(0.05, 0.01, 0.001), intercept.bottom = FALSE, out = 'Pre.html', intercept.top = TRUE, omit.stat = 'all')
```

**SEM Pre Analysis**
```{r}
#head(PLIC.Merged.df)

model <- '
  level: 1
  # measurement model
    Conf =~ Q7a_10_x + Q7a_11_x + Q7a_13_x
    Att =~ Q7b_1_x + Q7b_2_x + Q7b_4_x
    Eff =~ Q7c_1_x + Q7c_2_x + Q7b_3_x
    Q7b_1_x ~~ Q7b_2_x
    Q7b_3_x ~~ Q7b_4_x
    Att ~~ Eff
    Conf ~~ Eff
    Att ~~ Conf
  # regressions
    Conf ~ GenW + URM_Status
    Att ~ GenW + URM_Status
    Eff ~ GenW + URM_Status
    PreScores ~ GenW + URM_Status + MajorEng + MajorPhys + Conf + Att + Eff
  level: 2
    PreScores ~ Lab_Level
'

#fit <- sem(model, data = PLIC.PreOnly)
fit <- sem(model, data = PLIC.PreOnly.CR, cluster = 'Class_ID')
summary(fit, standardized = TRUE, fit.measures = TRUE, modindices = TRUE)
semPaths(fit, whatLabels = 'stand')
```

**MC Analysis**
```{r}
PLIC.MC <- PLIC.PreOnly %>%
  filter(!is.na(Q3c_x) & !is.na(Q4a_x)) %>%
  mutate(Q3C.Score = ifelse(Q3c_x == 2, 1, 0),
         Q4A.Score = ifelse(Q4a_x == 2, 1, 0),
         MC.Score = Q3C.Score + Q4A.Score)

t.test(PLIC.MC$MC.Score ~ PLIC.MC$Gender)
t.test(PLIC.MC$MC.Score ~ PLIC.MC$URM_Status)
```

**Likert Analysis**
```{r}
PLIC.Likert <- PLIC.PreOnly %>%
  filter(!is.na(Q2c_x) & !is.na(Q3a_x)) %>%
  mutate(Q2C.Score = case_when(
    Q2c_x > 3 ~ 1,
    Q2c_x < 3 ~ -1,
    Q2c_x == 3 ~ 0
  ),
  Q3A.Score = case_when(
    Q3a_x < 3 ~ 1,
    Q3a_x > 3 ~ -1,
    Q3a_x == 3 ~ 0
  ),
  Likert.Score = Q2C.Score + Q3A.Score)

t.test(PLIC.Likert$Likert.Score ~ PLIC.Likert$Gender)
t.test(PLIC.Likert$Likert.Score ~ PLIC.Likert$URM_Status)
```

**FR Analysis**
```{r}
PLIC.FR <- PLIC.PreOnly %>%
  filter(Survey_x == 'F') %>%
  filter(PreScores != 0)

hist(PLIC.FR$PreScores, breaks = 10)

t.test(PLIC.FR$PreScores ~ PLIC.FR$Gender)
t.test(PLIC.FR$PreScores ~ PLIC.FR$URM_Status)

cohen.d(PLIC.FR$PreScores ~ PLIC.FR$Gender)
cohen.d(PLIC.FR$PreScores ~ PLIC.FR$URM_Status)
```

