---
output:
  pdf_document: default
  html_document: default
---
# Load necessary packages
```{r, results = 'hide', message = FALSE, warning = FALSE}
library(tidyverse)
library(data.table)
library(reshape2)
library(ggpubr)
library(lmerTest)
library(sjPlot)
library(gridExtra)
library(stargazer)
library(lavaan)
library(semPlot)
theme_set(theme_classic(base_size = 14))
```

# Scoring/cleaning functions
```{r}
Read.Score <- function(file){
  dt <- fread(file)
  answers.cols <- names(dt)[grep('(a|b)$', names(dt))]
  
  dt[, (answers.cols) := lapply(.SD, function(x) case_when(x == 5 ~ 1,
                                                           x == 1 ~ -1,
                                                           TRUE ~ 0)),
     .SDcols = answers.cols]
  df <- dt[, -c('q40a', 'q40b')]

  df$student.score <- rowSums(df %>% select(grep("a$", names(.))))
  df$expert.score <- rowSums(df %>% select(grep("b$", names(.))))
  
  return(df)
}

Read.duplicate.cis <- function(file){
  cis.df <- read.csv(file)
  
  cis.noInfo <- cis.df[(cis.df$Q33 == '') | is.na(cis.df$Q33),]
  cis.FullInfo <- cis.df[(cis.df$Q33 != '') & !is.na(cis.df$Q33),]
  
  original.cols <- c('Q5', 'Q52',	'Q53', 'Q27', 'Q6',	'Q11', 'Q19',	'Q20', 'StartDate',
                     'anon_instructor_id', 'ResponseId', 'pre_survey_id', 'post_survey_id')

  cis.noInfo <- left_join(cis.noInfo, cis.FullInfo, 
                          by = c('anon_university_id', 'Q18'), 
                          suffix = c('.original', '.copy')) %>%
    select(anon_university_id, Q18, Q15.copy,	Q21.copy,	Q22_1.copy,	Q22_2.copy,	Q23.copy, 
           Q29.copy, grep('Q(3|4)\\d_?\\d?\\.copy', names(.)), 
           paste(original.cols, '.original', sep = '')) %>%
    filter(!duplicated(ResponseId.original) & !is.na(ResponseId.original)) %>%
    `colnames<-`(unlist(lapply(names(.), function (x) strsplit(x, '\\.')[[1]][1])))
  
  cis.df <- rbind(cis.FullInfo, cis.noInfo[, names(cis.df)])
  return(cis.df)
}
```

# Read, score, and match
```{r}
#cis.df <- Read.duplicate.cis('C:/Users/Cole/Documents/GRA_Summer2020/eclass-public-master/anon_cis.csv')

cis.df <- read.csv('C:/Users/Cole/Documents/GRA_Summer2020/eclass-public-master/anon_cis_CW.csv')

pre.df <- Read.Score('C:/Users/Cole/Documents/GRA_Summer2020/eclass-public-master/anon_pre.csv')

cis.pre.df <- right_join(cis.df, pre.df, by = c('pre_survey_id' = 'survey_id'))

post.df <- Read.Score('C:/Users/Cole/Documents/GRA_Summer2020/eclass-public-master/anon_post.csv')

full.df <- full_join(cis.pre.df, post.df, 
                     by = c('post_survey_id' = 'survey_id', 
                            'anon_student_id'), suffix = c('.pre', '.post'))

print('Total # of students in dataset...')
nrow(full.df)

print('Total # of classes in dataset...')
length(unique(full.df$ResponseId))

df.matched <- full.df %>%
  filter(!is.na(student.score.pre) & !is.na(student.score.post))

print('# of students in matched dataset...')
nrow(df.matched)

print('# of classes in matched dataset...')
length(unique(df.matched$ResponseId))
```

# Data processing
```{r}
df.matched <- df.matched %>%
  mutate(Major = case_when(
    Q48 == 1 ~ 'Physics',
    Q48 == 2 ~ 'Chemistry',
    Q48 == 3 ~ 'Biochemistry',
    Q48 == 4 ~ 'Biology',
    Q48 == 5 ~ 'Engineering',
    Q48 == 6 ~ 'Engineering Physics',
    Q48 == 7 ~ 'Astronomy',
    Q48 == 8 ~ 'Astrophysics',
    Q48 == 9 ~ 'Geology/geophysics',
    Q48 == 10 ~ 'Math/applied math',
    Q48 == 11 ~ 'Computer science',
    Q48 == 12 ~ 'Physiology',
    Q48 == 13 ~ 'Other science',
    Q48 == 14 ~ 'Non-science',
    Q48 == 15 ~ 'Open/undeclared',
    TRUE ~ 'Unknown'
  ),
  Gender = case_when(
    Q54 == 1 ~ 'Woman',
    Q54 == 2 ~ 'Man',
    Q54 == 3 ~ 'Other',
    TRUE ~ 'Unknown'
  ),
  Lab.goal = case_when(
    Q33 == 'Reinforce physics concepts.' ~ 'Concepts',
    Q33 == 'Both about equally.' ~ 'Both',
    Q33 == 'Develop lab skills.' ~ 'Skills',
    TRUE ~ NA_character_
  )) %>%
  mutate(Major = case_when(
    (Major == 'Physics') | (Major == 'Engineering Physics') | (Major == 'Astronomy') | 
      (Major == 'Astrophysics') ~ 'Physics',
    (Major == 'Chemistry') | (Major == 'Biochemistry') | (Major == 'Biology') | 
      (Major == 'Physiology') ~ 'Chem.LifeSci',
    Major == 'Engineering' ~ 'Engineering',
    (Major == 'Math/applied math') | (Major == 'Computer science') ~ 'Math.CS',
    (Major == 'Geology/geophysics') | (Major == 'Other science') ~ 'OtherSci',
    Major == 'Non-science' ~ 'NonSci',
    Major == 'Open/undeclared' ~ 'Undeclared',
    Major == 'Unknown' ~ 'Unknown',
    TRUE ~ NA_character_
  )) %>%
  mutate(Major = relevel(as.factor(Major), ref = 'Physics'),
         Gender = relevel(as.factor(Gender), ref = 'Man'),
         Lab.goal = relevel(as.factor(Lab.goal), ref = 'Concepts'))

df.matched$Race.ethnicity.Native = relevel(factor(ifelse((df.matched$Q52_5 == 1) | 
                                                      (df.matched$Q52_1 == 1), 1, 0),
                                                  levels = c(1, 0)), ref = '0')
new.race.cols <- c('Race.ethnicity.Other', 'Race.ethnicity.Black', 
                 'Race.ethnicity.Hispanic', 'Race.ethnicity.Asian', 
                 'Race.ethnicity.White', 'Race.ethnicity.Unknown')
setnames(df.matched, old = c('Q52_7', 'Q52_3', 'Q52_4', 'Q52_2', 'Q52_6', 
                             'race_unknown'), new = new.race.cols)
df.matched[is.na(df.matched)] <- 0
df.matched[new.race.cols] <- lapply(df.matched[new.race.cols], factor, levels = c(1, 0))
df.matched[new.race.cols] <- lapply(df.matched[new.race.cols], relevel, ref = '0')
```

# Data filtering
```{r}
# Remove whole classes without goal and/or level information
df.matched <- df.matched %>%
  filter(Lab.goal != '')

print('# of remaining students in matched dataset...')
nrow(df.matched)

print('# of remaining classes in matched dataset...')
length(unique(df.matched$ResponseId))
```

# Descriptive statistics
```{r}
plot.pre.post <- function(df, var){
  print(table(df[, var]))
  df.matched.long <- reshape2::melt(df, measure.vars = c('student.score.pre', 
                                                       'student.score.post'))
  
  p <- ggplot(df.matched.long, aes_string(x = var, y = 'value', group = 'variable', color = 'variable'))
  add_summary(p, fun = 'mean_se', group = c('variable')) +
    ylab('Score') +
    scale_color_manual(labels = c('pre', 'post'), values = c('#2271B2', '#D55E00')) +
    theme(axis.text.x = element_text(angle = 90))
}

plot.pre.post(df.matched, 'Major')
plot.pre.post(df.matched, 'Gender')
#plot.pre.post(df.matched, 'Race.ethnicity')
plot.pre.post(df.matched, 'Lab.goal')
```

# Mixed-effects models
```{r}
mod1 <- lmer(student.score.post ~ student.score.pre + Lab.goal + Major + 
               Gender + Race.ethnicity.Native + Race.ethnicity.Other +
               Race.ethnicity.Black + Race.ethnicity.Hispanic + Race.ethnicity.Asian + 
               Race.ethnicity.White + Race.ethnicity.Unknown + (1 | ResponseId), 
             df.matched)
summary(mod1)

mod2 <- lmer(student.score.post ~ student.score.pre + Lab.goal * 
               (Gender + Race.ethnicity.Native + Race.ethnicity.Other + 
                  Race.ethnicity.Black + Race.ethnicity.Hispanic + Race.ethnicity.Asian + 
                  Race.ethnicity.White + Race.ethnicity.Unknown) + Major + 
               (1 | ResponseId), df.matched)
summary(mod2)
```

# Marginal effects plots
```{r}
# Main effect of lab goal from Model 1
p1 <- plot_model(mod1, type = 'eff', terms = 'Lab.goal', dot.size = 4, line.size = 1, 
                 ci.lvl = 0.67, title = '', 
                 axis.title = 'Predicted E-CLASS posttest scores', 
                 colors = c('#e69f00', '#009e74', '#0071b2'), dodge = 0.5) +
  theme(legend.position = 'right') +
  scale_x_discrete(limits = c("Reinforce concepts", "Both about equally", 
                              "Develop skills"))

p1.new <- p1
p1.new$data$x <- c(1, 2, 3)
p1.new

# Effects of gender across lab goal from Model 2

p2 <- plot_model(mod2, type = 'eff', terms = c('Gender', 'Lab.goal'), dot.size = 4, 
                 line.size = 1, ci.lvl = 0.67, title = '', 
                 axis.title = 'Predicted E-CLASS posttest scores', 
                 colors = c('#e69f00', '#009e74', '#0071b2'), dodge = 0.5) +
  theme(legend.position = 'right')

p2.new <- p2
p2.new$data$group <- factor(p2.new$data$group, levels = c("Concepts", "Both", "Skills"))
p2.new
```

# Race/ethnicity marginal effects plots
```{r}
p3.native <- plot_model(mod2, type = 'eff', terms = c('Race.ethnicity.Native [1]', 
                                                      'Lab.goal'))
df.race.eff <- data.frame(p3.native$data) %>%
  mutate(race.ethnicity = 'Race.ethnicity.Native')
for(race in c(new.race.cols)){
  p3 <- plot_model(mod2, type = 'eff', terms = c(paste(race, ' [1]', sep = ''),
                                                 'Lab.goal'))
  df.race.eff <- rbind(df.race.eff, data.frame(p3$data) %>%
                         mutate(race.ethnicity = race))
}

df.race.eff <- df.race.eff %>%
  mutate(group = factor(group, levels = c('Concepts', 'Both', 'Skills'), 
                        ordered = TRUE)) %>%
  rowwise() %>%
  mutate(race.ethnicity = strsplit(race.ethnicity, '\\.')[[1]][3])

ggplot(df.race.eff, aes(x = race.ethnicity, y = predicted, group = group, color = group)) +
  geom_point(size = 4, position = position_dodge(width = 0.5)) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), size = 1, width = 0.2,
                position = position_dodge(width = 0.5)) +
  scale_color_manual(values = c('#e69f00', '#009e74', '#0071b2')) +
  labs(x = 'Race/ethnicity', y = 'Predicted E-CLASS posttest scores', color = 'Lab goal')
```

