---
output:
  pdf_document: default
  html_document: default
---
# Load necessary packages
```{r, results = 'hide', message = FALSE, warning = FALSE}
library(tidyverse)
library(data.table)
library(reshape2)
library(ggpubr)
library(lmerTest)
library(reghelper)
library(car)
library(lattice)
library(sjstats)
library(sjPlot)
library(gridExtra)
library(stargazer)
library(lavaan)
library(semPlot)
library(psych)
theme_set(theme_classic(base_size = 14))
source('C:/Users/Cole/Documents/GitHub/PLIC/Process-Merge-Concat/PLIC_DataProcessing.R')
```

# Read and match
```{r}
full.df <- fread('C:/Users/Cole/Documents/PLIC_DATA/Collective_Surveys/Complete/Complete_Concat_CourseInfo.csv') %>%
  filter(Survey_x == 'C' | Survey_y == 'C')

# Remove FR scores
full.df[full.df$Survey_x == 'F', 'PreScores'] <- NA_real_
full.df[full.df$Survey_y == 'F', 'PostScores'] <- NA_real_

print('Total # of students in dataset...')
length(unique(full.df$anon_student_id))

print('Total # of student records in dataset...')
nrow(full.df)

print('Total # of institutions in dataset..')
length(unique(full.df$anon_institution_id))

print('Total # of courses in dataset...')
length(unique(full.df$anon_course_id))

print('Total # of classes in dataset...')
length(unique(full.df$Class_ID))

# Remove whole classes without goal and/or level information or that were only administered at pre or post
full.df <- data.table(full.df)[, `:=`(N.students = .N, pre.rate = sum(Survey_x == 'C')/.N,
                                      post.rate = sum(Survey_y == 'C')/.N),  .(Class_ID)]

full.df <- full.df %>%
  filter(!is.na(Lab_level) & !is.na(Lab_purpose) & (Lab_purpose != '') & (pre.rate > 0) & 
           (post.rate > 0))

print('remaining # of students in dataset...')
length(unique(full.df$anon_student_id))

print('remaining # of student records in dataset...')
nrow(full.df)

print('remaining # of institutions in dataset..')
length(unique(full.df$anon_institution_id))

print('remaining # of courses in dataset...')
length(unique(full.df$anon_course_id))

print('remaining # of classes in dataset...')
length(unique(full.df$Class_ID))

df.matched <- full.df %>%
  filter(!is.na(PreScores) & !is.na(PostScores))

print('# of students in matched dataset...')
length(unique(df.matched$anon_student_id))

print('# of student records in matched dataset...')
nrow(df.matched)

print('# of institutions in matched dataset..')
length(unique(df.matched$anon_institution_id))

print('# of courses in matched dataset...')
length(unique(df.matched$anon_course_id))

print('# of classes in matched dataset...')
length(unique(df.matched$Class_ID))

table(df.matched[!duplicated(df.matched$anon_institution_id),
                 ]$Institution_type, exclude = NULL)
table(df.matched[!duplicated(df.matched$anon_course_id),]$Lab_level, exclude = NULL)
table(df.matched[!duplicated(df.matched$Class_ID),]$Lab_level, exclude = NULL)
table(df.matched[!duplicated(df.matched$anon_course_id),]$Lab_purpose, exclude = NULL)
table(df.matched[!duplicated(df.matched$Class_ID),]$Lab_purpose, exclude = NULL)
```

# Data processing
```{r}
# Creates new gender/race/major columns
df.matched <- Collapse.vars(df.matched) %>%
  mutate(Lab_level = relevel(as.factor(case_when(
    Lab_level == 'Intro-Algebra' ~ 'FY-Algebra',
    Lab_level == 'Intro-Calculus' ~ 'FY-Calculus',
    (Lab_level == 'Sophomore') | (Lab_level == 'Junior') | 
      (Lab_level == 'Senior') ~ 'BFY',
    TRUE ~ NA_character_
  )), ref= 'FY-Algebra'),
  Lab_purpose = relevel(as.factor(case_when(
    Lab_purpose == 'Reinforce concepts' ~ 'Concepts-based',
    Lab_purpose == 'Both about equally' ~ 'Mixed',
    Lab_purpose == 'Develop lab skills' ~ 'Skills-based')), ref = 'Concepts-based'))


df.matched[is.na(df.matched)] <- 0
df.matched[names(df.matched) %like% "Race"] <- 
  lapply(df.matched[names(df.matched) %like% "Race"], factor, levels = c(1, 0))
df.matched[names(df.matched) %like% "Race"] <- 
  lapply(df.matched[names(df.matched) %like% "Race"], relevel, ref = '0')
```

# Demographic breakdowns
```{r}
table(df.matched$Gender)
Race.ethnicity.table(df.matched, normalize = FALSE)
table(df.matched$Major)
table(df.matched$Lab_purpose)
table(df.matched$Gender, df.matched$Lab_purpose)
Race.ethnicity.table(df.matched, Lab.Purpose = TRUE)
table(df.matched$Major, df.matched$Lab_purpose)

chisq.test(df.matched[!duplicated(df.matched$Class_ID), 'Lab_purpose'], 
           df.matched[!duplicated(df.matched$Class_ID), 'Lab_level'])
summary(aov(PreScores ~ Lab_purpose, df.matched))
```

# Descriptive statistics
```{r}
plot.pre.post <- function(df, var){
  if(var == 'Race.ethnicity'){
    print(colSums(sapply(df[, names(df) %like% "Race"], 
                         function (x) as.numeric(as.character(x)))))
    
    df.long <- reshape2::melt(df.matched, id.vars = names(df)[names(df) %like% "Race"], 
                              measure.vars = c('PreScores', 'PostScores'),
                              variable.name = 'Time', value.name = 'Score') %>%
      reshape2::melt(., measure.vars = names(df)[names(df) %like% "Race"], 
                     id.vars = c('Time', 'Score'), variable.name = 'Race.ethnicity') %>%
      filter(value == 1) %>%
      select(Time, Score, Race.ethnicity) %>%
      rowwise() %>%
      mutate(Race.ethnicity = strsplit(as.character(Race.ethnicity), '\\.')[[1]][3])
    
  } else {
    print(table(df[, var]))
    df.long <- reshape2::melt(df, measure.vars = c('PreScores', 'PostScores'), 
                              variable.name = 'Time', value.name = 'Score')
  }
  
  p <- ggplot(df.long, aes_string(x = var, y = 'Score', group = 'Time', color = 'Time'))
  add_summary(p, fun = 'mean_se', group = c('Time')) +
    scale_color_manual(labels = c('pre', 'post'), values = c('#2271B2', '#D55E00')) +
    theme(axis.text.x = element_text(angle = 90))
}

plot.pre.post(df.matched, 'Major')
plot.pre.post(df.matched, 'Gender')
plot.pre.post(df.matched, 'Race.ethnicity')
plot.pre.post(df.matched, 'Lab_purpose')
```

# Mixed-effects models
```{r}
mod0 <- lmer(PostScores ~ (1 | anon_institution_id/Class_ID), df.matched)
r2(mod0)

mod <- lmer(PostScores ~ PreScores + Lab_level + Major + Lab_purpose * (Gender + 
               Race.ethnicity.AmInd + Race.ethnicity.Asian + Race.ethnicity.Black +
               Race.ethnicity.Hispanic + Race.ethnicity.NatHawaii +
               Race.ethnicity.White + Race.ethnicity.Other) + (1 | anon_institution_id/Class_ID), df.matched)
summary(mod)
r2(mod)

noStandard.cols <- c('Lab_purpose', 'Lab_level', 'Major', 'Gender', 
                     names(df.matched)[names(df.matched) %like% "Race"])
class(mod) <- "lmerMod"
mod.std <- beta(mod, skip = noStandard.cols)
```

# Variance inflation factors and model diagnostics
```{r}
vif(mod)
plot(mod, xlab = 'Fitted values', ylab = 'Residuals')
qqmath(mod)
```

# Output stargazer
```{r, results = 'hide', message = FALSE, warning = FALSE, include = FALSE}
rownames(mod.std$coefficients)[2] <- 'PreScores'

labels = c("Constant", "Pretest", "Both-based", "Skills-based", "BFY", "FY (calculus)",
           "Engineering", "Other", "Other Science", "Unknown", "Non-binary", "Unknown", 
           "Woman", "American Indian", "Asian", "Black", "Hispanic", "Native Hawaiian", 
           "White", "Other")

stargazer(mod, mod, mod, mod, coef = list(summary(mod)$coefficients[, 1], 
                                          summary(mod)$coefficients[, 2], 
                                          mod.std$coefficients[, 1], 
                                          mod.std$coefficients[, 2]), 
          se = list(summary(mod)$coefficients[, 2], NA, mod.std$coefficients[, 2], NA), 
          type='latex', intercept.bottom = FALSE, style = 'asr', keep.stat = c('n'), 
          column.labels = c('Beta', 'SE', 'Beta.std', 'SE'), model.numbers = FALSE, 
          covariate.labels = labels, dep.var.labels = 'PLIC posttest scores', 
          out ='PLIC_models.tex')
```

# Marginal effects plots
```{r}
# Main effect of lab goal
p1 <- plot_model(mod, type = 'eff', terms = 'Lab_purpose', dot.size = 4, line.size = 1, 
                 ci.lvl = 0.67, title = '', 
                 axis.title = 'Predicted PLIC posttest scores', 
                 colors = c('#e69f00', '#009e74', '#0071b2'), dodge = 0.5) +
  theme(legend.position = 'right') +
  xlab('')

theme_set(theme_classic(base_size = 25))
p1
p1$data

# Effects of gender across lab goal
p2 <- plot_model(mod, type = 'eff', terms = c('Gender', 'Lab_purpose'), dot.size = 4, 
                 line.size = 1, ci.lvl = 0.67, title = '', 
                 axis.title = 'Predicted PLIC posttest scores', 
                 colors = c('#e69f00', '#009e74', '#0071b2'), dodge = 0.5) +
  theme(legend.position = 'right') +
  scale_x_discrete(limits = c("Man", "Non-binary", "Woman", "Unknown")) +
  labs(color = 'Lab purpose')

p2.new <- p2
p2.new$data$group <- factor(p2.new$data$group, levels = c("Concepts-based", "Mixed", "Skills-based"))
p2.new$data$x <- rep(c(1, 2, 4, 3), 3)
p2.new
```

# Race/ethnicity marginal effects plots
```{r}
p3.other <- plot_model(mod, type = 'eff', terms = c('Race.ethnicity.Other [1]', 
                                                      'Lab_purpose'))
df.race.eff <- data.frame(p3.other$data) %>%
  mutate(race.ethnicity = 'Race.ethnicity.Other')
for(race in c('Race.ethnicity.AmInd', 'Race.ethnicity.Asian', 'Race.ethnicity.Black', 
              'Race.ethnicity.Hispanic', 'Race.ethnicity.NatHawaii', 
              'Race.ethnicity.White')){
  p3 <- plot_model(mod, type = 'eff', terms = c(paste(race, ' [1]', sep = ''),
                                                 'Lab_purpose'))
  df.race.eff <- rbind(df.race.eff, data.frame(p3$data) %>%
                         mutate(race.ethnicity = race))
}

df.race.eff <- df.race.eff %>%
  mutate(group = factor(group, levels = c("Concepts-based", "Mixed", "Skills-based"),
                        ordered = TRUE)) %>%
  rowwise() %>%
  mutate(race.ethnicity = strsplit(race.ethnicity, '\\.')[[1]][3])

ggplot(df.race.eff, aes(x = race.ethnicity, y = predicted, group = group, color = group)) +
  geom_point(size = 4, position = position_dodge(width = 0.5)) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), size = 1, width = 0.2,
                position = position_dodge(width = 0.5)) +
  scale_color_manual(values = c('#e69f00', '#009e74', '#0071b2')) +
  labs(x = 'Race/ethnicity', y = 'Predicted PLIC posttest scores', color = 'Lab purpose')
```

```{r}
df.race.eff <- df.race.eff %>%
  mutate(race.ethnicity = case_when(
    race.ethnicity == 'AmInd' ~ 'American Indian',
    race.ethnicity == 'NatHawaii' ~ 'Native Hawaiian',
    TRUE ~ race.ethnicity
  ),
  var = 'Race/ethnicity')

df.gender <- data.frame(p2.new$data) %>%
  mutate(gender = case_when(
    x == 1 ~ 'Man',
    x == 2 ~ 'Non-binary',
    x == 3 ~ 'Woman',
    x == 4 ~ 'Unknown'
  ),
  var = 'Gender')

cols <- c('x', 'predicted', 'std.error', 'conf.low', 'conf.high', 'lab', 'group', 'var')
colnames(df.race.eff) <- cols
colnames(df.gender) <- cols

df.demos <- rbind(df.race.eff, df.gender)

theme_set(theme_classic(base_size = 9))
ggplot(df.demos, aes(x = factor(group, levels = c('Man', 'Non-binary', 'Woman', 
                                                  'American Indian', 'Asian', 'Black',  
                                                  'Hispanic', 'Native Hawaiian', 'White', 
                                                  'Other', 'Unknown')), y = predicted, 
                     group = lab, color = lab)) +
  geom_point(size = 3, position = position_dodge(width = 0.7)) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), size = 1, width = 0.2,
                position = position_dodge(width = 0.7)) +
  scale_color_manual(values = c('#e69f00', '#009e74', '#0071b2')) +
  labs(x = '', y = 'Predicted PLIC posttest scores', color = 'Lab type') +
  facet_wrap(~var, scales = 'free_x') +
  theme(legend.position = 'top') +
  theme(axis.text.x = element_text(angle = 40, vjust = 1, hjust = 1))
```

```{r}
df.matched[, names(df.matched) %like% "Q29|Q31"] <- 
  data.frame(lapply(df.matched[, names(df.matched) %like% "Q29|Q31"], function(x) 
    droplevels(factor(as.vector(x), levels = c('1', '2', '3', '4', '5'), 
                      ordered = TRUE))))

df.matched[, names(df.matched) %like% "Q29|Q31"] <- data.frame(lapply(df.matched[, names(df.matched) %like% "Q29|Q31"], function(x) as.numeric(x)))
```

# SEM with fixed measurement model
```{r}
df.matched <- df.matched %>%
  mutate(Lab.goal.skills = 1 * (Lab_purpose == 'Skills-based'),
         Lab.goal.both = 1 * (Lab_purpose == 'Mixed'),
         Lab.goal.concepts = 1 * (Lab_purpose == 'Concepts-based'))

mod.sem <- '
  level: 1
    PostScores ~ PreScores
  level: 2
    decision =~ 1.0 * Q29_1 + 1.310 * Q29_2 + 1.122 * Q29_3 + 1.013 * Q29_4 + 0.807 * Q29_5 + 0.906 * Q31_6
    #epistemic =~ 1.0 * Q31_1 + 0.990 * Q31_2 + 0.899 * Q31_4 + 0.593 * Q31_5

    #decision ~~ 0.241 * epistemic
    #Q31_1 ~~ 0.131 * Q31_2 + -0.004 * Q31_3
    #Q31_2 ~~ 0.165 * Q31_4
    #Q31_3 ~~ 0.344 * Q31_4
    Q29_1 ~~ 0.524 * Q29_1
    Q29_2 ~~ 0.297 * Q29_2
    Q29_3 ~~ 0.645 * Q29_3
    Q29_4 ~~ 0.570 * Q29_4
    Q29_5 ~~ 0.632 * Q29_5
    Q31_6 ~~ 0.630 * Q31_6
    #Q31_1 ~~ 0.379 * Q31_1
    #Q31_2 ~~ 0.272 * Q31_2
    #Q31_4 ~~ 0.532 * Q31_4
    #Q31_5 ~~ 0.561 * Q31_5
    decision ~~ 0.556 * decision
    #epistemic ~~ 0.534 * epistemic

    decision ~ Lab.goal.skills + Lab.goal.both
    #epistemic ~ Lab.goal.skills + Lab.goal.both

    PostScores ~ decision + Lab.goal.skills + Lab.goal.both
'

fit <- sem(mod.sem, data = df.matched, cluster = "Class_ID")
summary(fit, standardized = TRUE, fit.measures = TRUE, modindices = TRUE)
standardizedsolution(fit)
resid(fit, type = 'cor')
```

# Compare to null model
```{r}
library(semTools)
nullRMSEA(fit)
```

```{r}
df.matched[, names(df.matched) %like% "Q29|Q31"] <- 
  data.frame(lapply(df.matched[, names(df.matched) %like% "Q29|Q31"], function(x) 
    droplevels(factor(as.vector(x), levels = c('1', '2', '3', '4', '5'), 
                      ordered = TRUE))))

df.matched[, names(df.matched) %like% "Q29|Q31"] <- data.frame(lapply(df.matched[, names(df.matched) %like% "Q29|Q31"], function(x) as.numeric(x)))
```

# SEM with fixed measurement model
```{r}
df.matched <- df.matched %>%
  mutate(Lab.goal.skills = 1 * (Lab_purpose == 'Skills-based'),
         Lab.goal.both = 1 * (Lab_purpose == 'Mixed'),
         Lab.goal.concepts = 1 * (Lab_purpose == 'Concepts-based'),
         Lab.level.FYAlg = 1 * (Lab_level == 'FY-Alg'),
         Lab.level.FYCal = 1 * (Lab_level == 'FY-Calculus'),
         Lab.level.BFY = 1 * (Lab_level == 'BFY'))

mod.sem <- '
  level: 1
    PostScores ~ PreScores
  level: 2
    decision =~ Q29_1 + Q29_2 + Q29_3 + Q29_4 + Q29_5 + Q31_6
    #epistemic =~ Q31_1 + Q31_2 + Q31_4 + Q31_5

    #decision ~~ epistemic

    decision ~ Lab.goal.skills + Lab.goal.both
    #epistemic ~ Lab.goal.skills + Lab.goal.both

    PostScores ~ decision + Lab.goal.skills + Lab.goal.both
'

fit <- sem(mod.sem, data = df.matched, cluster = "Class_ID")
summary(fit, standardized = TRUE, fit.measures = TRUE, modindices = TRUE)
standardizedsolution(fit)
resid(fit, type = 'cor')
```