---
output:
  pdf_document: default
  html_document: default
---
# Load necessary packages
```{r, results = 'hide', message = FALSE, warning = FALSE}
library(easypackages)
libraries('tidyverse', 'data.table', 'reshape2', 'ggpubr', 'lmerTest',
          'reghelper', 'car', 'lattice', 'sjstats', 'sjPlot', 'gridExtra',
          'stargazer', 'lavaan', 'semPlot', 'psych', 'grid', 'semTools')
theme_set(theme_classic(base_size = 12)) # set font size for ggplot
source('C:/Users/Cole/Documents/GitHub/PLIC/Processing-Scripts/PLIC_DataProcessing.R')
```

# Read and match
```{r}
full.df <- read.csv('C:/Users/Cole/Documents/DATA/PLIC_DATA/Collective_Surveys/Complete/Complete_Concat_CourseInfo.csv') %>%
  filter(Survey_x == 'C' | Survey_y == 'C') %>% # remove events with no CR surveys
  # remove pre-pandemic data
  mutate(V4_x = as.Date(V4_x),
         V4_y = as.Date(V4_y)) %>%
  filter(V4_y < as.Date('2020-01-01') | (is.na(V4_y) & 
                                           V4_x < as.Date('2020-01-01')))

# Remove FR scores
#full.df[(full.df$Survey_x == 'F') | is.na(full.df$Q3c_x), 'PreScores'] <- NA_real_
#full.df[(full.df$Survey_y == 'F') | is.na(full.df$Q3c_y), 'PostScores'] <- NA_real_
full.df[(full.df$Survey_x == 'F'), 'PreScores'] <- NA_real_
full.df[(full.df$Survey_y == 'F'), 'PostScores'] <- NA_real_
full.df <- full.df %>%
  filter(!is.na(PreScores) | !is.na(PostScores))

print('Total # of students in dataset...')
length(unique(full.df$anon_student_id))

print('Total # of student records in dataset...')
nrow(full.df)

print('Total # of institutions in dataset..')
length(unique(full.df$anon_institution_id))

print('Total # of courses in dataset...')
length(unique(full.df$anon_course_id))

print('Total # of classes in dataset...')
length(unique(full.df$Class_ID))

# Remove whole classes without goal and/or level information or that were only administered at pre or post
full.df <- data.table(full.df)[, `:=`(N.students = .N, 
                                      pre.rate = sum(Survey_x == 'C')/.N,
                                      post.rate = sum(Survey_y == 'C')/.N),  
                               .(Class_ID)]

full.df <- full.df %>%
  filter(!is.na(Lab_level) & !is.na(Lab_purpose) & (Lab_purpose != '') & 
           (pre.rate > 0) & (post.rate > 0))

print('remaining # of students in dataset...')
length(unique(full.df$anon_student_id))

print('remaining # of student records in dataset...')
nrow(full.df)

print('remaining # of institutions in dataset..')
length(unique(full.df$anon_institution_id))

print('remaining # of courses in dataset...')
length(unique(full.df$anon_course_id))

print('remaining # of classes in dataset...')
length(unique(full.df$Class_ID))

df.matched <- full.df %>%
  filter(!is.na(PreScores) & !is.na(PostScores))

print('# of students in matched dataset...')
length(unique(df.matched$anon_student_id))

print('# of student records in matched dataset...')
nrow(df.matched)

print('# of institutions in matched dataset..')
length(unique(df.matched$anon_institution_id))

print('# of courses in matched dataset...')
length(unique(df.matched$anon_course_id))

print('# of classes in matched dataset...')
length(unique(df.matched$Class_ID))

table(df.matched[!duplicated(df.matched$anon_institution_id),
                 ]$Institution_type, exclude = NULL)
table(df.matched[!duplicated(df.matched$anon_course_id),]$Lab_level, 
      exclude = NULL)
table(df.matched[!duplicated(df.matched$Class_ID),]$Lab_level, exclude = NULL)
table(df.matched[!duplicated(df.matched$anon_course_id),]$Lab_purpose, 
      exclude = NULL)
table(df.matched[!duplicated(df.matched$Class_ID),]$Lab_purpose, exclude = NULL)
```

# Data processing
```{r}
# Creates new gender/race/major columns
df.matched <- Collapse.vars(data.frame(df.matched)) %>%
  mutate(Lab_level = relevel(as.factor(case_when(
    (Lab_level == 'Intro-Algebra') | (Lab_level == 'Intro-Calculus') ~ 'FY',
    (Lab_level == 'Sophomore') | (Lab_level == 'Junior') | 
      (Lab_level == 'Senior') | (Lab_level == 'Graduate') ~ 'BFY',
    TRUE ~ NA_character_
  )), ref = 'FY'),
  Lab_purpose = relevel(as.factor(case_when(
    Lab_purpose == 'Reinforce concepts' ~ 'Concepts-based',
    Lab_purpose == 'Both about equally' ~ 'Mixed',
    Lab_purpose == 'Develop lab skills' ~ 'Skills-based')), 
    ref = 'Concepts-based'))
```

# Demographic breakdowns
```{r}
df.matched[, colnames(df.matched) %like% 
             'Race.ethnicity'][is.na(df.matched[, colnames(df.matched) 
                                                %like% 'Race.ethnicity'])] <- 0
table(df.matched$Gender)
Race.ethnicity.table(df.matched, normalize = FALSE)
table(df.matched$Major)
table(df.matched$Lab_purpose)
table(df.matched$Gender, df.matched$Lab_purpose)
Race.ethnicity.table(df.matched, Lab.Purpose = TRUE)
table(df.matched$Major, df.matched$Lab_purpose)
```

# Descriptive statistics
```{r}
plot.pre.post <- function(df, var){
  if(var == 'Race.ethnicity'){
    print(colSums(sapply(df[, names(df) %like% "Race"], 
                         function (x) as.numeric(as.character(x)))))
    
    df.long <- reshape2::melt(df.matched, 
                              id.vars = names(df)[names(df) %like% "Race"], 
                              measure.vars = c('PreScores', 'PostScores'),
                              variable.name = 'Time', value.name = 'Score') %>%
      reshape2::melt(., measure.vars = names(df)[names(df) %like% "Race"], 
                     id.vars = c('Time', 'Score'), 
                     variable.name = 'Race.ethnicity') %>%
      filter(value == 1) %>%
      select(Time, Score, Race.ethnicity) %>%
      rowwise() %>%
      mutate(Race.ethnicity = strsplit(as.character(Race.ethnicity), 
                                       '\\.')[[1]][3])
    
  } else {
    print(table(df[, var]))
    df.long <- reshape2::melt(df, measure.vars = c('PreScores', 'PostScores'), 
                              variable.name = 'Time', value.name = 'Score')
  }
  
  p <- ggplot(df.long, aes_string(x = var, y = 'Score', group = 'Time', 
                                  color = 'Time'))
  add_summary(p, fun = 'mean_se', group = c('Time')) +
    scale_color_manual(labels = c('pre', 'post'), 
                       values = c('#2271B2', '#D55E00')) +
    theme(axis.text.x = element_text(angle = 90))
}

plot.pre.post(df.matched, 'Major')
plot.pre.post(df.matched, 'Gender')
plot.pre.post(df.matched, 'Race.ethnicity')
plot.pre.post(df.matched, 'Lab_purpose')
```

# Mixed-effects models
```{r}
mod0 <- lmer(PostScores ~ (1 | anon_institution_id/Class_ID), df.matched)
r2(mod0)

mod <- lmer(PostScores ~ PreScores + Lab_level + Lab_purpose * 
              (Gender + Race.ethnicity.AmInd + Race.ethnicity.Asian + 
                 Race.ethnicity.Black + Race.ethnicity.Hispanic + 
                 Race.ethnicity.NatHawaii + Race.ethnicity.White + 
                 Race.ethnicity.Other) + Major + 
              (1 | anon_institution_id/Class_ID), df.matched)
summary(mod)
r2(mod)

class(mod) <- "lmerMod"
mod.std <- std_beta(mod, ci = 0.67)
mod.std$uncertainty <- abs(mod.std$Std_Coefficient - mod.std$CI_low)
```

# Variance inflation factors and model diagnostics
```{r}
vif(mod)
plot(mod, xlab = 'Fitted values', ylab = 'Residuals')
qqmath(mod)
```

# Output stargazer
```{r, results = 'hide', message = FALSE, warning = FALSE, include = FALSE}
labels = c("Constant", "Pretest", "BFY", "Mixed", "Skills-based", "Non-binary", 
           "Unknown",  "Woman", "American Indian", "Asian", "Black", "Hispanic", 
           "Native Hawaiian", "White", "Other", "Engineering", "Other", 
           "Other Science", "Unknown", "Mixed * Non-binary", 
           "Skills-based * Non-binary", "Mixed * Unknown", 
           "Skills-based * Unknown", "Mixed * Woman", "Skills-based * Woman", 
           "Mixed * American Indian", "Skills-based * American Indian", 
           "Mixed * Native Hawaiian", "Skills-based * Native Hawaiian", 
           "Mixed * Other",  "Skills-based * Other", "Mixed * Black", 
           "Skills-based * Black", "Mixed * Hispanic", "Skills-based * Hispanic", 
           "Mixed * Asian", "Skills-based * Asian", "Mixed * White", 
           "Skills-based * White", "Mixed * Unknown", "Skills-based * Unknown")

stargazer(mod, mod, mod, mod, coef = list(summary(mod)$coefficients[, 1],
                                          summary(mod)$coefficients[, 2], 
                                          mod.std$Std_Coefficient,
                                          mod.std$uncertainty), 
          se = list(summary(mod)$coefficients[, 2], NA, 
                    mod.std$uncertainty, NA), 
          type = 'latex', intercept.bottom = FALSE, style = 'asr', 
          keep.stat = c('n'), column.labels = c('Beta', 'SE', 'Beta.std', 'SE'), 
          model.numbers = FALSE, covariate.labels = labels, 
          dep.var.labels = 'PLIC posttest scores', out ='PLIC_models.tex')
```

# Marginal effects plots
```{r}
# Main effect of lab goal
p1 <- plot_model(mod, type = 'eff', terms = 'Lab_purpose', ci.lvl = 0.67)

p1.new <- ggplot(data.frame(p1$data), aes(x = factor(x), y = predicted, 
                                          color = factor(x))) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), size = 1, width = 0,
                position = position_dodge(width = 0.5)) +
  scale_x_discrete(labels = c('Concepts-based', 'Mixed', 'Skills-based')) +
  scale_color_manual(values = c('#e69f00', '#009e74', '#0071b2')) +
  labs(x = 'Lab type', y = 'Predicted PLIC posttest scores') +
  theme(axis.text.x = element_text(angle = 40, vjust = 1, hjust = 1),
        legend.position = 'none')

# Effects of gender across lab goal
p2 <- plot_model(mod, type = 'eff', terms = c('Gender', 'Lab_purpose'), 
                 dot.size = 2, 
                 line.size = 1, ci.lvl = 0.67, title = '', 
                 axis.title = '', 
                 colors = c('#e69f00', '#009e74', '#0071b2'), dodge = 0.5) +
  scale_x_discrete(limits = c("Man", "Non-binary", "Woman", "Unknown")) +
  labs(x = 'Gender', y = '', color = 'Lab type') +
  theme(legend.position = 'top')

p2.new <- p2
p2.new$data$x <- rep(c(1, 2, 4, 3), 3)

get_legend <- function(myggplot){
  # from http://www.sthda.com/english/wiki/wiki.php?id_contents=7930
  tmp <- ggplot_gtable(ggplot_build(myggplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)
}

leg <- get_legend(p2.new)
p2.new <- p2.new + theme(legend.position = 'none',
                         axis.text.x = element_text(angle = 40, vjust = 1, 
                                                    hjust = 1),
                         plot.margin = unit(c(0, 0, 0, -0.5), 'cm'))
```

# Race/ethnicity marginal effects plots
```{r}
p3.other <- plot_model(mod, type = 'eff', terms = c('Race.ethnicity.Other [1]', 
                                                      'Lab_purpose'), 
                       ci.lvl = 0.67)
df.race.eff <- data.frame(p3.other$data) %>%
  mutate(race.ethnicity = 'Race.ethnicity.Other')
for(race in c('Race.ethnicity.AmInd', 'Race.ethnicity.Asian',
              'Race.ethnicity.Black', 'Race.ethnicity.Hispanic', 
              'Race.ethnicity.NatHawaii', 'Race.ethnicity.White')){
  p3 <- plot_model(mod, type = 'eff', terms = c(paste(race, ' [1]', sep = ''),
                                                 'Lab_purpose'), ci.lvl = 0.67)
  df.race.eff <- rbind(df.race.eff, data.frame(p3$data) %>%
                         mutate(race.ethnicity = race))
}

# ...and clean up the dataframe a little bit
df.race.eff <- df.race.eff %>%
  rowwise() %>%
  mutate(race.ethnicity = strsplit(race.ethnicity, '\\.')[[1]][3]) %>%
  mutate(group = factor(group, levels = c('Concepts-based', 'Mixed', 
                                          'Skills-based'), ordered = TRUE),
         race.ethnicity = case_when(
           race.ethnicity == 'AmInd' ~ 'American Indian',
           race.ethnicity == 'NatHawaii' ~ 'Native Hawaiian',
           TRUE ~ race.ethnicity))

p3 <- ggplot(df.race.eff, aes(x = factor(race.ethnicity, 
                                         levels = c('American Indian', 'Asian', 
                                                    'Black', 'Hispanic', 
                                                    'Native Hawaiian', 'White', 
                                                    'Other')), 
                        y = predicted, group = group, color = group)) +
  geom_point(size = 2, position = position_dodge(width = 0.5)) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), size = 1, width = 0.2,
                position = position_dodge(width = 0.5)) +
  scale_color_manual(values = c('#e69f00', '#009e74', '#0071b2')) +
  labs(x = 'Race/ethnicity', y = '') +
  theme(axis.text.x = element_text(angle = 40, vjust = 1, hjust = 1),
        legend.position = 'none',
        plot.margin = unit(c(0, 0, 0, -0.5), 'cm'))
```

```{r}
png('Figures/PLIC_Labtype_Demos.png', width = 586, height = 363)
grobs = cbind(ggplotGrob(p1.new), ggplotGrob(p2.new), ggplotGrob(p3), 
              size = "first")
grid.arrange(leg, arrangeGrob(grobs), heights = c(1, 10))
dev.off()
```

# Process CIS items
```{r}
df.matched[, names(df.matched) %like% "Q28|Q29|Q31|Q32|Q33"] <- 
  data.frame(lapply(df.matched[, names(df.matched) %like% "Q28|Q29|Q31|Q32|Q33"], 
                    function(x) droplevels(factor(as.vector(x), 
                                                  levels = c('1', '2', '3', '4',
                                                             '5'), 
                                                  ordered = TRUE))))

df.matched[, names(df.matched) %like% "Q28|Q29|Q31|Q32|Q33"] <- data.frame(lapply(df.matched[, names(df.matched) %like% "Q28|Q29|Q31|Q32|Q33"],                                                           function(x) as.numeric(x)))
```

# SEM with fixed measurement model
```{r}
df.matched <- df.matched %>%
  mutate(Lab.goal.skills = 1 * (Lab_purpose == 'Skills-based'),
         Lab.goal.both = 1 * (Lab_purpose == 'Mixed'),
         Lab.goal.concepts = 1 * (Lab_purpose == 'Concepts-based'))

df.FY <- df.matched %>%
  filter(Lab_level == 'FY')
df.BFY <- df.matched %>%
  filter(Lab_level == 'BFY')

mod.agency <- '
  level: 1
    PostScores ~ PreScores
  level: 2
    agency =~ Q29_1 + Q29_2 + Q29_3 + Q29_4 + Q29_5 + Q28_3 + Q31_6

    agency ~ Lab.goal.skills + Lab.goal.both

    PostScores ~ agency + Lab.goal.skills + Lab.goal.both
'

mod.modeling <- '
  level: 1
    PostScores ~ PreScores
  level: 2
    modeling =~ Q31_1 + Q31_2 + Q31_3 + Q31_4

    modeling ~ Lab.goal.skills + Lab.goal.both

    PostScores ~ modeling + Lab.goal.skills + Lab.goal.both
'

mod.communication <- '
  level: 1
    PostScores ~ PreScores
  level: 2
    communication =~ Q33_1 + Q33_2 + Q33_3 + Q33_4

    communication ~ Lab.goal.skills + Lab.goal.both

    PostScores ~ communication + Lab.goal.skills + Lab.goal.both
'


fit <- sem(mod.agency, data = df.matched, cluster = "Class_ID")
summary(fit, standardized = TRUE, fit.measures = TRUE, modindices = TRUE)
standardizedsolution(fit)
resid(fit, type = 'cor')

fit <- sem(mod.modeling, data = df.matched, cluster = "Class_ID")
summary(fit, standardized = TRUE, fit.measures = TRUE, modindices = TRUE)
standardizedsolution(fit)
resid(fit, type = 'cor')

fit <- sem(mod.communication, data = df.matched, cluster = "Class_ID")
summary(fit, standardized = TRUE, fit.measures = TRUE, modindices = TRUE)
standardizedsolution(fit)
resid(fit, type = 'cor')
```