---
output:
  pdf_document: default
  html_document: default
---
# Load necessary packages
```{r, results = 'hide', message = FALSE, warning = FALSE}
library(tidyverse)
library(xlsx)
library(data.table)
library(lavaan)
library(semPlot)
```

# E-CLASS scoring function
```{r}
answers <- read.xlsx('C:/Users/Cole/Documents/ECLASS_DATA/Answers_Template.xlsx', sheetName = 'Converted', rowIndex = c(2, 4), header = FALSE)

colnames(answers) <- as.character(unlist(answers[2,]))
answers <- answers[1,]
answers <- as.data.frame(t(answers)) %>%
  `colnames<-`(c('Answer')) %>%
  mutate(Question = row.names(.)) %>%
  filter(!grepl('\\.1$', Question)) %>%
  mutate(Answer = case_when(
    Answer == 'A' ~ 1,
    Answer == 'D' ~ -1,
    TRUE ~ NA_real_
  )) %>%
  filter(!is.na(Answer))

answers <- data.frame(t(answers)) %>%
  `colnames<-`(as.character(unlist(.[2,]))) %>%
  slice(., 1)

answers.cols <- names(answers)

Read.Score.ECLASS <- function(file){
  dt <- fread(file)
  
  dt[, (answers.cols) := lapply(.SD, function(x) case_when(x >= 4 ~ 1,
                                                           x <= 2 ~ -1,
                                                           TRUE ~ 0)),
     .SDcols = answers.cols]
  
  scores.df <- sweep(dt[, ..answers.cols], 2, 
                     as.numeric(as.character(unlist(answers))), "*")
  
  scores.df$student.score <- rowSums(scores.df %>% select(grep("a$", names(.))))
  scores.df$expert.score <- rowSums(scores.df %>% select(grep("b$", names(.))))
  
  df <- cbind(dt, scores.df[, c('student.score', 'expert.score')]) %>%
    filter((V10 == 1) & (q40a == 4)) %>% # remove students that didn't finish/click filter
  select(Q3_1_TEXT, Q3_2_TEXT, Q3_3_TEXT, student.score, expert.score) %>%
  `colnames<-`(c('first.name', 'last.name', 'ID', 'student.score', 'expert.score'))
  return(df)
}
```

# Read E-CLASS files
```{r}
# Fall 2017

df.ECLASS.P1116.F2017pre <- Read.Score.ECLASS('C:/Users/Cole/Documents/ECLASS_DATA/Raw_Surveys/Fall2017/PRE/Fall2017PRE-Cornell University-Phys-1116-Natasha_Holmes-ezo65e90NlkpwRD.csv')

df.ECLASS.P1116.F2017post <- Read.Score.ECLASS('C:/Users/Cole/Documents/ECLASS_DATA/Raw_Surveys/Fall2017/POST/Fall2017POST-Cornell University-Phys-1116-Natasha_Holmes-e9iS05zkYUGdsc5.csv')

df.ECLASS.P2217.F2017pre <- Read.Score.ECLASS('C:/Users/Cole/Documents/ECLASS_DATA/Raw_Surveys/Fall2017/PRE/Fall2017PRE-Cornell University-Phys-2217-Natasha_Holmes-1ZCOw6uPVntmS7b.csv')

df.ECLASS.P2217.F2017post <- Read.Score.ECLASS('C:/Users/Cole/Documents/ECLASS_DATA/Raw_Surveys/Fall2017/POST/Fall2017POST-Cornell University-Phys-2217-Natasha_Holmes-6SBVr7ddgt7D2Pr.csv')

df.ECLASS.P2218.F2017pre <- Read.Score.ECLASS('C:/Users/Cole/Documents/ECLASS_DATA/Raw_Surveys/Fall2017/PRE/Fall2017PRE-Cornell University-Phys-2218-Natasha_Holmes-0cwmwYnSpRKeTDT.csv')

df.ECLASS.P2218.F2017post <- Read.Score.ECLASS('C:/Users/Cole/Documents/ECLASS_DATA/Raw_Surveys/Fall2017/POST/Fall2017POST-Cornell University-Phys-2218-Natasha_Holmes-9uIb86xtOdbM0ct.csv')

# Spring 2018

df.ECLASS.P1116.S2018pre <- Read.Score.ECLASS('C:/Users/Cole/Documents/ECLASS_DATA/Raw_Surveys/Spring2018/PRE/Spring2018PRE-Cornell University-Phys-1116-Natasha_Holmes-3P10x8a4zSQJd6B.csv')

df.ECLASS.P1116.S2018post <- Read.Score.ECLASS('C:/Users/Cole/Documents/ECLASS_DATA/Raw_Surveys/Spring2018/POST/Spring2018POST-Cornell University-Phys-1116-Natasha_Holmes-db4nkuge13zi1h3.csv')

# Fall 2018

df.ECLASS.P1112.F2018pre <- Read.Score.ECLASS('C:/Users/Cole/Documents/ECLASS_DATA/Raw_Surveys/Fall2018/PRE/Fall2018PRE-Cornell-Phys-1112-Natasha_Holmes-8k2QpdWGDMHCV6t.csv')

df.ECLASS.P1112.F2018post <- Read.Score.ECLASS('C:/Users/Cole/Documents/ECLASS_DATA/Raw_Surveys/Fall2018/POST/Fall2018POST-Cornell-Phys-1112-Natasha_Holmes-8942bcaRSDUniDj.csv')

df.ECLASS.P1116.F2018pre <- Read.Score.ECLASS('C:/Users/Cole/Documents/ECLASS_DATA/Raw_Surveys/Fall2018/PRE/Fall2018PRE-Cornell University-Phys-1116-Natasha_Holmes-40K8e3vdsXRnyeh.csv')

df.ECLASS.P1116.F2018post <- Read.Score.ECLASS('C:/Users/Cole/Documents/ECLASS_DATA/Raw_Surveys/Fall2018/POST/Fall2018POST-Cornell University-Phys-1116-Natasha_Holmes-5ArscxVeockVPJb.csv')
```

# Read PLIC files
```{r}
Get.PLIC.data <- function(df, ClassID){
  df.class <- df %>%
    filter(Class_ID == ClassID) %>%
    select(-Class_ID) %>%
    `colnames<-`(c('ID', 'last.name', 'first.name', 'PLIC.score'))
  
  return(df.class)
}

### Pre ###

df.PLIC.pre <- fread('C:/Users/Cole/Documents/PLIC_DATA/Collective_Surveys/Complete/Complete_Concat.csv') %>%
  filter(!is.na(PreScores)) %>%
  select(Class_ID, Q5a_x, Q5b_x, Q5c_x, PreScores)

df.PLIC.post <- fread('C:/Users/Cole/Documents/PLIC_DATA/Collective_Surveys/Complete/Complete_Concat.csv') %>%
  filter(!is.na(PostScores)) %>%
  select(Class_ID, Q5a_y, Q5b_y, Q5c_y, PostScores)

# Fall 2017

df.PLIC.P1116.F2017pre <- Get.PLIC.data(df.PLIC.pre, 'R_1Oko8BpPfb9rt0G')
df.PLIC.P1116.F2017post <- Get.PLIC.data(df.PLIC.post, 'R_1Oko8BpPfb9rt0G')
df.PLIC.P2217.F2017pre <- Get.PLIC.data(df.PLIC.pre, 'R_12QFe4VQPh6oNW1')
df.PLIC.P2217.F2017post <- Get.PLIC.data(df.PLIC.post, 'R_12QFe4VQPh6oNW1')
df.PLIC.P2218.F2017pre <- Get.PLIC.data(df.PLIC.pre, 'R_2Y4jnzAgBixC4Qm')
df.PLIC.P2218.F2017post <- Get.PLIC.data(df.PLIC.post, 'R_2Y4jnzAgBixC4Qm')

# Spring 2018

df.PLIC.P1116.S2018pre <- Get.PLIC.data(df.PLIC.pre, 'R_2R8MnTyv2jFgPzA')
df.PLIC.P1116.S2018post <- Get.PLIC.data(df.PLIC.post, 'R_2R8MnTyv2jFgPzA')

# Fall 2018

df.PLIC.P1112.F2018pre <- Get.PLIC.data(df.PLIC.pre, 'R_3ijRcPfXo8MUfFj')
df.PLIC.P1112.F2018post <- Get.PLIC.data(df.PLIC.post, 'R_3ijRcPfXo8MUfFj')
df.PLIC.P1116.F2018pre <- Get.PLIC.data(df.PLIC.pre, 'R_1IB300CxBKh0Tw7')
df.PLIC.P1116.F2018post <- Get.PLIC.data(df.PLIC.post, 'R_1IB300CxBKh0Tw7')
```

# Matching E-CLASS and PLIC
```{r}
match.ECLASS.PLIC <- function(ECLASS.df, PLIC.df){
  match.cols <- c('ID', 'last.name', 'first.name')
  ECLASS.df[, match.cols] <- sapply(ECLASS.df[, match.cols], tolower)
  PLIC.df[, match.cols] <- sapply(PLIC.df[, match.cols], tolower)
  
  names.df <- inner_join(ECLASS.df, PLIC.df, by = c('first.name', 'last.name'), 
                         suffix = c('', '.copy'))[, c(match.cols, 'student.score', 
                                                      'expert.score', 'PLIC.score')]
  ID.df <- inner_join(ECLASS.df, PLIC.df, by = c('ID'), 
                      suffix = c('', '.copy'))[, c(match.cols, 'student.score',
                                                   'expert.score', 'PLIC.score')]

match.df <- rbind(names.df, ID.df) %>%
  filter(!duplicated(ID))
}

P1116.F2017pre.df <- match.ECLASS.PLIC(df.ECLASS.P1116.F2017pre, df.PLIC.P1116.F2017pre)
P2217.F2017pre.df <- match.ECLASS.PLIC(df.ECLASS.P2217.F2017pre, df.PLIC.P2217.F2017pre)
P2218.F2017pre.df <- match.ECLASS.PLIC(df.ECLASS.P2218.F2017pre, df.PLIC.P2218.F2017pre)
P1116.S2018pre.df <- match.ECLASS.PLIC(df.ECLASS.P1116.S2018pre, df.PLIC.P1116.S2018pre)
P1112.F2018pre.df <- match.ECLASS.PLIC(df.ECLASS.P1112.F2018pre, df.PLIC.P1112.F2018pre)
P1116.F2018pre.df <- match.ECLASS.PLIC(df.ECLASS.P1116.F2018pre, df.PLIC.P1116.F2018pre)

pre.df <- rbind(P1116.F2017pre.df, P2217.F2017pre.df, P2218.F2017pre.df, 
                P1116.S2018pre.df, P1112.F2018pre.df, P1116.F2018pre.df)

P1116.F2017post.df <- match.ECLASS.PLIC(df.ECLASS.P1116.F2017post, df.PLIC.P1116.F2017post)
P2217.F2017post.df <- match.ECLASS.PLIC(df.ECLASS.P2217.F2017post, df.PLIC.P2217.F2017post)
P2218.F2017post.df <- match.ECLASS.PLIC(df.ECLASS.P2218.F2017post, df.PLIC.P2218.F2017post)
P1116.S2018post.df <- match.ECLASS.PLIC(df.ECLASS.P1116.S2018post, df.PLIC.P1116.S2018post)
P1112.F2018post.df <- match.ECLASS.PLIC(df.ECLASS.P1112.F2018post, df.PLIC.P1112.F2018post)
P1116.F2018post.df <- match.ECLASS.PLIC(df.ECLASS.P1116.F2018post, df.PLIC.P1116.F2018post)

post.df <- rbind(P1116.F2017post.df, P2217.F2017post.df, P2218.F2017post.df, 
                 P1116.S2018post.df, P1112.F2018post.df, P1116.F2018post.df)
```

# Correlation and visualization (PRE)
```{r}
nrow(pre.df)

hist(pre.df$student.score)
hist(pre.df$PLIC.score)

cor(pre.df$student.score, pre.df$PLIC.score)
plot(pre.df$student.score, pre.df$PLIC.score)
```

# Correlation and visualization (POST)
```{r}
nrow(post.df)

hist(post.df$student.score)
hist(post.df$PLIC.score)

cor(post.df$student.score, post.df$PLIC.score)
plot(post.df$student.score, post.df$PLIC.score)
```

# SEM analysis
```{r}
names.df <- inner_join(pre.df, post.df, by = c('first.name', 'last.name'), 
                       suffix = c('.pre', '.post')) %>%
  select(-ID.post)
colnames(names.df)[1] <- 'ID'

ID.df <- inner_join(pre.df, post.df, by = c('ID'), 
                       suffix = c('.pre', '.post')) %>%
  select(-c('first.name.post', 'last.name.post'))
colnames(ID.df)[c(2, 3)] <- c('last.name', 'first.name')

df <- rbind(names.df, ID.df) %>%
  filter(!duplicated(ID)) %>%
  select(student.score.pre, student.score.post, PLIC.score.pre, PLIC.score.post)

mod <- '
  PLIC.score.pre ~ student.score.pre
  student.score.post ~ student.score.pre + PLIC.score.pre
  PLIC.score.post ~ PLIC.score.pre + student.score.post
'

fit <- sem(mod, df)
summary(fit, standardized = TRUE, fit.measures = TRUE, modindices = TRUE)
semPaths(fit, whatLabels = 'std', edge.color = 'black', edge.label.cex = 1.5, curve = 2, sizeMan = 12, nodeLabels = c('PLIC pre', 'E-CLASS\npost', 'PLIC post', 'E-CLASS\npre'), residuals = FALSE, label.scale = FALSE, mar = c(8, 8, 8, 8))
```